spring:
  application:
    name: api-gateway  # can register itself in the registry
  cloud:
    gateway:  # let it know that is gateway
      routes:  # do route
      - id: TeacherService  # should be unique for every route
        uri: lb://TeacherService  # go to the TeacherService and do Lb : lb assuming we have multiple teacherServices
        predicates:
        - Path=/teachers/**   # Means if i got this request send it to the above url
      - id: StudentService
        uri: lb://StudentService
        predicates:
        - Path=/student/**
            
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ #gateway is registered as a client


