spring:
  cloud:
    gateway:
      routes:
        - id: UserService
          uri: lb://USERSERVICE
          predicates:
            - Path=/users/**
        - id: AvatarService
          uri: lb://AVATARSERVICE
          predicates:
            - Path=/avatar/**
        - id: ElementService
          uri: lb://ELEMENTSERVICE
          predicates:
            - Path=/element/**
        - id: RewardService
          uri: lb://REWARDSERVICE
          predicates:
            - Path=/rewards/**
        - id: SchoolService
          uri: lb://SCHOOLSERVICE
          predicates:
            - Path=/school/**
        - id: StudentService
          uri: lb://STUDENTSERVICE
          predicates:
            - Path=/students/**
        - id: StudentRewardService
          uri: lb://STUDENTREWARDSERVICE
          predicates:
            - Path=/student-rewards/**
        - id: TeacherService
          uri: lb://TEACHERSERVICE
          predicates:
            - Path=/teachers/**
        - id: TeacherCommandService
          uri: lb://TEACHERCOMMANDSERVICE
          predicates:
            - Path=/teacher-command/**
        - id: StudentCommandService
          uri: lb://STUDENTCOMMANDSERVICE
          predicates:
            - Path=/student-command/**
        - id: LoginService
          uri: lb://LOGINSERVICE
          predicates:
            - Path=/login/**