spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: gid
  zipkin:
    base-url: http://localhost:9411/
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/